Improve validation errors for assay attachments
instedd/cdx pull request #1475
Opened 2022-02-21 13:27 UTC by straight-shoota

This resolves part of #1456. Nice error messages related to assay files are not yet resolved, pending a revisit of the feature.

2022-02-21 18:05 UTC, ysbaddaden approved these changes
:+1:

2022-02-22 13:48 UTC, diegoliberman commented
@straight-shoota I made a mistake.  The LOINC code isn't mandatory.  I don't know what I was thinking.  Thanks @devduarte for spotting this.

2022-02-22 13:49 UTC, devduarte requested changes

2022-02-22 13:49 UTC, diegoliberman commented on app/models/assay_attachment.rb
> +  validates_presence_of :loinc_code
DiegoD is right, the LOINC code isn't mandatory.

2022-02-22 13:52 UTC, ysbaddaden commented on app/models/assay_attachment.rb
> +  validates_presence_of :loinc_code
@diegoliberman But when present, we should verify that its value is valid?

2022-02-23 14:42 UTC, devduarte approved these changes
🚀 🍟

2022-02-23 16:15 UTC, diegoliberman approved these changes

2022-02-23 17:07 UTC, merged