Disable send icon according to selected qc samples
instedd/cdx pull request #1540
Opened 2022-03-15 03:05 UTC by devduarte

Fixes: #1525

Before this fix we were disabling (or not) the icon based on the last row change. This fix checks for all the selected sample list every-time a checkbox change event happens.

Note: branched from #1484 because I'm reusing a modified function from that branch.

2022-03-15 10:06 UTC, straight-shoota approved these changes

2022-03-18 09:09 UTC, ysbaddaden requested changes
Just a tiny optimization, then please merge!

2022-03-18 09:09 UTC, ysbaddaden commented on app/views/samples/_index_bulk_actions_js.haml
> +    var areQc = selectedSamplesIds().filter((sample) => sample.isQc === true).length
You can just ask whether the collection contains a QC sample with [Array.prototype.some()](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/some). This has two benefits: 1. you don't allocate another array and 2. the iteration will stop as soon as a QC sample is found.

```javascript
if (selectedSamplesId().some(sample => sample.isQc)) {
  // at least one selected sample is a QC
}
```

2022-03-22 10:01 UTC, ysbaddaden approved these changes

2022-03-22 10:01 UTC, merged