Feature/1696 defend against spam
instedd/cdx pull request #1796
Opened 2022-11-16 17:20 UTC by omelao

In my opinion the best approach is set the AWS WAF Bot control. But....as we need Mati to implement this, I installed Google Recaptcha V2 on Register form. I tried recpatcha v3 with the same gem, but it doesn't work. `recaptcha_v3` returns `undefined method`.

To test it you must go to `/users/registration/sign_up` page.

2022-11-16 17:30 UTC, omelao commented
I tried the last comment of [this](https://github.com/ambethia/recaptcha/issues/296) also....and it doesn't installed the gem.

2022-11-20 17:33 UTC, ysbaddaden requested changes
Let's make the feature opt-in, so it's disabled by default and we won't need to deal with it in development and tests but also in production when it's not needed.

Then it shall be ready to merge.

2022-11-20 17:33 UTC, ysbaddaden commented on docker-dev.env
> +RECAPTCHA_SECRET_KEY_V3=6LeLkv0iAAAAAAZi7HvBkxPW-BDcigTDJQtdj0iV
Security Rule: NEVER commit credentials, it's unsafe even for private repositories.

Don't forget to invalidate and regenerate these keys.

```suggestion
```

2022-11-20 17:33 UTC, ysbaddaden commented on config/settings.yml
> +  secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
Let's add the ability to disable the feature. It should be opt-in (i.e. disabled by default).

```suggestion
recaptcha:
  enabled: <%= ENV["RECAPTCHA_ENABLED"] == "1" %>
  site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
```

Of course wherever we use recaptcha we should wrap it with `if Settings.recaptcha.enabled`.

2022-11-20 17:33 UTC, ysbaddaden commented on config/initializers/recaptcha.rb
> +  config.secret_key = ENV['RECAPTCHA_SECRET_KEY']
Let's use the settings

```suggestion
  config.site_key = Settings.recaptcha.site_key
  config.secret_key = Settings.recaptcha.secret_key
```

2022-11-21 16:27 UTC, ysbaddaden approved these changes

2022-11-21 16:38 UTC, merged