Add (Un)Blind Samples Button on Box Detail
instedd/cdx pull request #1804
Opened 2022-11-18 15:37 UTC by omelao

Just for Owners/Creators, if a box is transfered it will not show the button.

![image](https://user-images.githubusercontent.com/19227697/202742534-bd6de378-3bbb-4796-bcf2-24c03ed82823.png)

![image](https://user-images.githubusercontent.com/19227697/202742593-defeeee0-dc5d-434f-9b32-7b3f640497d5.png)

2022-11-20 17:14 UTC, ysbaddaden requested changes
Nice! Just a few readability enhancements, but most importantly the authorization to improve.

2022-11-20 17:14 UTC, ysbaddaden commented on app/models/box.rb
> +    self.update(blinded: false)
`self` is implicit in Ruby, you don't have to specify it (same in `#blind!`). You may also want to use [#update_columns](https://api.rubyonrails.org/v6.1/classes/ActiveRecord/Persistence.html#method-i-update_columns) which would be a bit faster (no need to re-validate the box, we only change one value):

```suggestion
    update_columns(blinded: false)
```

Same for `#blind!`

2022-11-20 17:14 UTC, ysbaddaden commented on app/controllers/boxes_controller.rb
> +    @can_blind = @box.box_transfers.count == 0
We have a method for that (it's a little faster as it won't even run a COUNT in SQL):

```suggestion
    @can_blind = !@box.transferred?
```

2022-11-20 17:14 UTC, ysbaddaden commented on app/controllers/boxes_controller.rb
> +    return unless authorize_resource(@box, UPDATE_BOX)
Sadly, this won't do. Once the box is added to a transfer we won't show the blind/unblind button, but once the transfer is confirmed, the receiver institution will own the box, and thus be authorized to blind/unblind by forging the request.

A basic `return head :forbidden if @box.transferred?` should work for now.

2022-11-29 09:44 UTC, ysbaddaden commented
@omelao Can I bother you to add controller specs for the `boxes#blind` and `boxes#unblind` actions, to ensure that they work as expected?

- context: before transfer
  - owner institution can blind box
  - owner institution can unblind box

- context: after transfer
  - owner institution can't blind box
  - owner institution can't unblind box
  - sender institution can unblind box after transfer

Those specs are important to ensure that we don't inadvertently break the authorizations later!

2022-11-29 13:00 UTC, omelao commented
Yeah. Sure.

2022-12-01 23:28 UTC, omelao commented
@ysbaddaden done

2022-12-02 13:22 UTC, merged