Adapt form error UI to design
instedd/cdx pull request #1939
Opened 2023-05-17 13:34 UTC by bolom

Adjusts the UI for form errors according to https://invis.io/Z7OD63XAWKF#/467087061_New_Sample_-_Erros

2023-05-17 13:46 UTC, leandroradusky commented
I was performing a smoke test, and it seems to work OK. **But**, there is an odd change on the date pickers:

Before (`main` branch): 

![image](https://github.com/instedd/cdx/assets/13782680/80186078-7a1f-45c1-8e8c-77fe4edb2cd2)

After:

![image](https://github.com/instedd/cdx/assets/13782680/65199a2a-46f1-4ecf-8e00-b858e1388c02)

Same is happening with all the date pickers.

2023-05-19 00:54 UTC, bolom commented
@leandroradusky  I've updated the css

2023-05-19 08:55 UTC, leandroradusky approved these changes
I went through the code & tested it locally and it looks good!

2023-05-23 08:37 UTC, ysbaddaden requested changes
Thanks @bolom but I'm kinda lost: why bring 28de0127e55d8ead250ea8b8ce5fd8e12bc9fcac from #1689 which we closed as too complex in favor to #1706? The only commit we want in is f0b6086ebea6970c99bce700e10ab681af2a560b from #1682, rebased from `main` and without the above commit from #1689.

Related slack discussion: 
https://manas.slack.com/archives/C034BR64J/p1684274918617989?thread_ts=1684268802.208069&cid=C034BR64J

I just tried a `git cherry-pick f0b6086ebea6970c99bce700e10ab681af2a560b` and the commit applies cleanly on top of main. Once `CdxFormHelper#has_errors?` is fixed, the design is in.

2023-05-23 08:37 UTC, ysbaddaden commented on app/helpers/cdx_form_helper.rb
> +    )
I don't know how the new Sentry gem is working, but I just verified the legacy Raven source code, and we must specify the `extra:` key (see `Raven::Event.new`).

```ruby
    Raven.capture_message("Unhandled form errors", extra: {
      form: object_name,
      errors: unhandled_errors,
    })
```

2023-05-23 08:37 UTC, ysbaddaden commented on app/helpers/cdx_form_helper.rb
> +    message = "Unhandled form errors in #{object_name}: #{unhandled_errors}"
Where does the `object_name` variable come from?

2023-05-23 14:16 UTC, bolom commented
@ysbaddaden voila, pushed my commit with your requests.

2023-05-30 06:43 UTC, ysbaddaden approved these changes
Perfect!

2023-05-30 10:09 UTC, merged